spring.application.name=demo
server.port=8090

# --- Base de datos H2 en memoria ---
spring.datasource.url=jdbc:h2:file:./mydatabase
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# --- Consola web de H2 (http://localhost:8090/h2) ---
spring.h2.console.enabled=true
spring.h2.console.path=/h2

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
